name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:          # correr manualmente em Actions â†’ Run workflow
  schedule:
    - cron: "0 0 * * 0"       # opcional: 1x por semana (domingo, 00:00 UTC)

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'https://weiitt.github.io/livro-de-receitas-xops/'
          allow_issue_writing: false
          cmd_options: ''
